<a href="https://colab.research.google.com/github/sandeshghule/generativeAI/blob/main/Assignment2/RandomFeedNeuralNetworkClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import numpy as np

# Load the wine dataset
wine = pd.read_csv('/content/sample_data/wine.data.csv', header=None, skiprows=1)
X = wine.iloc[:, 1:].values
y = wine.iloc[:, 0].values

# Separate features (X) and target variable (y)
X = wine.iloc[:, 1:].values
y = wine.iloc[:, 0].values


# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)


# Scale the data using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# Define the first neural network architecture
mlp1 = MLPClassifier(hidden_layer_sizes=(10, 5), max_iter=1000, random_state=42)
mlp1.fit(X_train, y_train)

# Make predictions on the test data
y_pred1 = mlp1.predict(X_test)


# Evaluate model 1
accuracy1 = accuracy_score(y_test, y_pred1)
f1_1 = f1_score(y_test, y_pred1, average='weighted')
cm1 = confusion_matrix(y_test, y_pred1)

print("Model 1:")
print(f"Accuracy: {accuracy1:.4f}")
print(f"F1-score: {f1_1:.4f}")
print("Confusion Matrix:\n", cm1)


# Define the second neural network architecture
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=42)

mlp2 = MLPClassifier(hidden_layer_sizes=(20, 10, 5), activation='relu', solver='adam', max_iter=2000, random_state=42)
mlp2.fit(X_train, y_train)

# Make predictions on the test data
y_pred2 = mlp2.predict(X_test)


# Evaluate model 2
accuracy2 = accuracy_score(y_test, y_pred2)
f1_2 = f1_score(y_test, y_pred2, average='weighted')
cm2 = confusion_matrix(y_test, y_pred2)

print("\nModel 2:")
print(f"Accuracy: {accuracy2:.4f}")
print(f"F1-score: {f1_2:.4f}")
print("Confusion Matrix:\n", cm2)


Model 1:
Accuracy: 0.9438
F1-score: 0.9433
Confusion Matrix:
 [[32  1  0]
 [ 3 30  1]
 [ 0  0 22]]

Model 2:
Accuracy: 0.7826
F1-score: 0.7808
Confusion Matrix:
 [[50  6  0]
 [ 5 47  9]
 [13  2 29]]
